Bump Airflor to 1.10.2
Repository is now apache/airflow as it seems like Airflow is not
in incubation anymore.

I'm using the version tag instead of the commit hash, that should
reduce confusion.

For some reason I had to set `SLUGIFY_USES_TEXT_UNIDECODE=true`
to avoid getting the following weird GPL error message:

> RuntimeError: By default one of Airflow's dependencies installs a GPL
> dependency (unidecode). To avoid this dependency set
> SLUGIFY_USES_TEXT_UNIDECODE=yes in your environment when you install
> or upgrade Airflow. To force installing the GPL version set
> AIRFLOW_GPL_UNIDECODE

See Airflow CHANGELOG: https://github.com/apache/airflow/blob/master/CHANGELOG.txt